// This file was generated by lezer-generator. You probably shouldn't edit it.
export const
  LineComment = 1,
  PixelAsmProgram = 2,
  FunctionLabel = 3,
  Instruction = 4,
  Opcode = 5,
  Data = 6,
  Number = 7,
  PCOffset = 8,
  Colour = 9,
  Label = 10
