// This file was generated by lezer-generator. You probably shouldn't edit it.
import {LRParser} from "@lezer/lr"
import {highlighting} from "./pixel-asm-highlight.js"
export const parser = LRParser.deserialize({
  version: 14,
  states: "!dQYQPOOObQPO'#C`OvQPO'#CgO{QPO'#CgQYQPOOOOQO'#Cb'#CbOOQO,58z,58zO!QQPO,59ROOQO,59R,59ROOQO-E6e-E6eOOQO1G.m1G.m",
  stateData: "![~O^OSPOS~ORQOTPO~ORTOVTOWTOXTOYTO`SX~O_VO~O`WO~O`YO~OWXPX~",
  goto: "j[PPPP]PaPPPPdTROSRUPQSORXS",
  nodeNames: "⚠ LineComment PixelAsmProgram FunctionLabel Instruction Opcode Data Number PCOffset Colour Label",
  maxTerm: 16,
  propSources: [highlighting],
  skippedNodes: [0,1],
  repeatNodeCount: 1,
  tokenData: "5i~RjXY!sYZ#U]^!spq!sst#Z!O!P(z!Q![*T![!]*f!}#O*k#T#U+c#V#W,f#W#X.c#X#Y/b#Z#[/h#[#]0V#]#^1O#^#_1e#`#a1k#a#b1}#b#c2g#c#d2p#d#e2y#f#g4^#g#h4v#j#k!s#k#l5V~!xS^~XY!s]^!spq!s#j#k!s~#ZO`~~#`[P~OY$UZ!Q$U!Q![$m![!c$U!c!i$m!i!r$U!r!s%d!s#T$U#T#Z$m#Z;'S$U;'S;=`$g<%lO$U~$ZSP~OY$UZ;'S$U;'S;=`$g<%lO$U~$jP;=`<%l$U~$tYX~P~OY$UZ!Q$U!Q![$m![!c$U!c!i$m!i#T$U#T#Z$m#Z;'S$U;'S;=`$g<%lO$U~%iUP~OY$UZ!e$U!e!f%{!f;'S$U;'S;=`$g<%lO$U~&QWP~OY$UZ{$U{|&j|}$U}!O&j!O;'S$U;'S;=`$g<%lO$U~&oWP~OY$UZ!O$U!O!P'X!P!Q$U!Q![(Z![;'S$U;'S;=`$g<%lO$U~'^UP~OY$UZ!Q$U!Q!['p![;'S$U;'S;=`$g<%lO$U~'wUW~P~OY$UZ!Q$U!Q!['p![;'S$U;'S;=`$g<%lO$U~(bWW~P~OY$UZ!O$U!O!P'X!P!Q$U!Q![(Z![;'S$U;'S;=`$g<%lO$U~(}S!Q![)Z!c!})c#R#S)c#T#o)c~)`PV~!Q![)Z~)fS!Q![)r!c!})r#R#S)r#T#o)r~)wSR~!Q![)r!c!})r#R#S)r#T#o)r~*YQV~!O!P*`!Q![*T~*cP!Q![)Z~*kO_~~*nP!Q![*q~*tR!Q![*q![!]*}#P#Q+^~+QP!Q![+T~+WQ!Q![+T#P#Q+^~+cOY~~+fR#W#X+o#`#a+z#b#c+o~+rP#W#X+u~+zOT~~+}P#`#a,Q~,TP#c#d,W~,ZP#V#W,^~,cPT~#T#U+u~,iS#T#U,u#Y#Z-R#^#_-k#`#a.P~,xP#`#a,{~-OP#`#a+u~-UP#f#g-X~-[P#T#U-_~-bP#a#b-e~-hP#X#Y+u~-nP#a#b-q~-tP#d#e-w~-|PT~!S!T+u~.SP#X#Y.V~.YP#T#U.]~.`P#f#g+u~.fR#X#Y.o#]#^/U#i#j/[~.rQ#V#W+u#`#a.x~.{P#T#U/O~/RP#m#n+u~/XP#j#k+u~/_P#d#e+u~/eP#e#f+u~/kQ#X#Y/q#h#i+u~/vPT~#h#i/y~/|P#V#W0P~0SP#[#].V~0YQ#T#U0`#X#Y0l~0cP#`#a0f~0iP#h#i+u~0oP#]#^0r~0uP#Z#[0x~0{P#[#]0f~1RQ#b#c1X#f#g1_~1[P#V#W+u~1bP#b#c+o~1hP#a#b/[~1nR#W#X1w#X#Y+u#h#i+u~1zP#T#U+u~2QR#T#U2Z#]#^2a#i#j,{~2^P#l#m+u~2dP#b#c+u~2jQ#X#Y/b#c#d0f~2sQ#Y#Z-R#f#g+u~2|R#]#^3V#f#g3q#i#j3}~3YP#l#m3]~3`P#X#Y3c~3fP#`#a3i~3nPT~#f#g+u~3tP#]#^3w~3zP#b#c0f~4QQ#g#h4W#h#i/y~4ZP#[#]+u~4aQ#X#Y4g#c#d4p~4jQ#T#U+o#h#i+u~4sP#i#j1_~4yQ#h#i,^#i#j5P~5SP#U#V+u~5YP#]#^5]~5`P#W#X5c~5fP#h#i4W",
  tokenizers: [0],
  topRules: {"PixelAsmProgram":[0,2]},
  tokenPrec: 53
})
