// This file was generated by lezer-generator. You probably shouldn't edit it.
import {LRParser} from "@lezer/lr"
import {highlighting} from "./pixel-asm-highlight.js"
export const parser = LRParser.deserialize({
  version: 14,
  states: "!dQYQPOOObQPO'#C`OvQPO'#CgO{QPO'#CgQYQPOOOOQO'#Cb'#CbOOQO,58z,58zO!QQPO,59ROOQO,59R,59ROOQO-E6e-E6eOOQO1G.m1G.m",
  stateData: "![~O^OSPOS~ORQOTPO~ORTOVTOWTOXTOYTO`SX~O_VO~O`WO~O`YO~OWXPX~",
  goto: "j[PPPP]PaPPPPdTROSRUPQSORXS",
  nodeNames: "⚠ LineComment PixelAsmProgram FunctionLabel Instruction Opcode Data Number PCOffset Colour Label",
  maxTerm: 16,
  propSources: [highlighting],
  skippedNodes: [0,1],
  repeatNodeCount: 1,
  tokenData: "4w~RjXY!sYZ#U]^!spq!sst#Z!O!P(z!Q![*T![!]*f!}#O*k#T#U+c#V#W,f#W#X.c#X#Y/b#Z#[/h#[#]/q#]#^0j#^#_1P#`#a1V#a#b1i#b#c2R#c#d2[#d#e2e#f#g3u#g#h4U#j#k!s#k#l4e~!xS^~XY!s]^!spq!s#j#k!s~#ZO`~~#`[P~OY$UZ!Q$U!Q![$m![!c$U!c!i$m!i!r$U!r!s%d!s#T$U#T#Z$m#Z;'S$U;'S;=`$g<%lO$U~$ZSP~OY$UZ;'S$U;'S;=`$g<%lO$U~$jP;=`<%l$U~$tYX~P~OY$UZ!Q$U!Q![$m![!c$U!c!i$m!i#T$U#T#Z$m#Z;'S$U;'S;=`$g<%lO$U~%iUP~OY$UZ!e$U!e!f%{!f;'S$U;'S;=`$g<%lO$U~&QWP~OY$UZ{$U{|&j|}$U}!O&j!O;'S$U;'S;=`$g<%lO$U~&oWP~OY$UZ!O$U!O!P'X!P!Q$U!Q![(Z![;'S$U;'S;=`$g<%lO$U~'^UP~OY$UZ!Q$U!Q!['p![;'S$U;'S;=`$g<%lO$U~'wUW~P~OY$UZ!Q$U!Q!['p![;'S$U;'S;=`$g<%lO$U~(bWW~P~OY$UZ!O$U!O!P'X!P!Q$U!Q![(Z![;'S$U;'S;=`$g<%lO$U~(}S!Q![)Z!c!})c#R#S)c#T#o)c~)`PV~!Q![)Z~)fS!Q![)r!c!})r#R#S)r#T#o)r~)wSR~!Q![)r!c!})r#R#S)r#T#o)r~*YQV~!O!P*`!Q![*T~*cP!Q![)Z~*kO_~~*nP!Q![*q~*tR!Q![*q![!]*}#P#Q+^~+QP!Q![+T~+WQ!Q![+T#P#Q+^~+cOY~~+fR#W#X+o#`#a+z#b#c+o~+rP#W#X+u~+zOT~~+}P#`#a,Q~,TP#c#d,W~,ZP#V#W,^~,cPT~#T#U+u~,iS#T#U,u#Y#Z-R#^#_-k#`#a.P~,xP#`#a,{~-OP#`#a+u~-UP#f#g-X~-[P#T#U-_~-bP#a#b-e~-hP#X#Y+u~-nP#a#b-q~-tP#d#e-w~-|PT~!S!T+u~.SP#X#Y.V~.YP#T#U.]~.`P#f#g+u~.fR#X#Y.o#]#^/U#i#j/[~.rQ#V#W+u#`#a.x~.{P#T#U/O~/RP#m#n+u~/XP#j#k+u~/_P#d#e+u~/eP#e#f+u~/kQ#X#Y+u#h#i+u~/tQ#T#U/z#X#Y0W~/}P#`#a0Q~0TP#h#i+u~0ZP#]#^0^~0aP#Z#[0d~0gP#[#]0Q~0mQ#b#c0s#f#g0y~0vP#V#W+u~0|P#b#c+o~1SP#a#b/[~1YR#W#X1c#X#Y+u#h#i+u~1fP#T#U+u~1lR#T#U1u#]#^1{#i#j,{~1xP#l#m+u~2OP#b#c+u~2UQ#X#Y/b#c#d0Q~2_Q#Y#Z-R#f#g+u~2hR#]#^2q#f#g3]#i#j3i~2tP#l#m2w~2zP#X#Y2}~3QP#`#a3T~3YPT~#f#g+u~3`P#]#^3c~3fP#b#c0Q~3lP#g#h3o~3rP#[#]+u~3xP#X#Y3{~4OQ#T#U+o#h#i+u~4XQ#h#i,^#i#j4_~4bP#U#V+u~4hP#]#^4k~4nP#W#X4q~4tP#h#i3o",
  tokenizers: [0],
  topRules: {"PixelAsmProgram":[0,2]},
  tokenPrec: 53
})
